Feature/switch display plan order
KitaharaMugiro/deepl_english_learning pull request #56
Opened 2022-11-13 14:03 UTC by web3rakko

無料プランカードのdescriptionの修正などはありますが、取り急ぎ出来るところまで以下の2タスクについて進めました。

- [料金表の並び順を変更する](https://trello.com/c/TF063XUn/)
- [料金表に”無料”を入れる](https://trello.com/c/FZbBcGzR/)

また、インデントなどを合わせたいと考えているのですが、すみません、使われているtypescriptのフォーマッターについて教えていただけますでしょうか。

2022-11-13 23:39 UTC, KitaharaMugiro requested changes

2022-11-13 23:39 UTC, KitaharaMugiro commented on app/models/const/PlanConst.ts
> +    priceId: process.env.NODE_ENV === "development" ? "price_1KFP2gFZt1qcfPgxhqpUz2az" : "price_1KFP5kFZt1qcfPgxKao0ExVC",
こちらnull(or undefined)が良いですね！
priceIdはStripeから発行されるIDになっています。

2022-11-13 23:39 UTC, KitaharaMugiro commented on app/components/price/PlanBoxGroup.tsx
> +                <div onClick={() => {if(!p.isFree){ return payment(p.priceId)}}}>
isFreeフラグを新たに作るよりpriceIdの有無で飛ばすかどうか決める方がカラム数が増えなくてよいかと思いました！

2022-11-13 23:39 UTC, KitaharaMugiro commented on app/models/const/PlanConst.ts
> +    features: ["まずはお試し","ビギナー用"],
無料で何ができるのか知りたいような気がしますね。
どういう文章にしたらいいんだろう。
「お試し問題1問/日」「英語日記」「まずはお試し」
とかでどうでしょう？

2022-11-14 14:56 UTC, web3rakko commented on app/models/const/PlanConst.ts
> +    priceId: process.env.NODE_ENV === "development" ? "price_1KFP2gFZt1qcfPgxhqpUz2az" : "price_1KFP5kFZt1qcfPgxKao0ExVC",
ありがとうございます！修正します！

2022-11-14 14:56 UTC, web3rakko commented on app/components/price/PlanBoxGroup.tsx
> +                <div onClick={() => {if(!p.isFree){ return payment(p.priceId)}}}>
はい、上と併せてこちらも修正します！

2022-11-14 14:57 UTC, web3rakko commented on app/models/const/PlanConst.ts
> +    features: ["まずはお試し","ビギナー用"],
ありがとうございます！そうですよね、無料で何が出来るかを訴求するのが確かに大事でした。
すごく良いと思いました！

2022-11-17 14:05 UTC, KitaharaMugiro approved these changes

2022-11-17 14:06 UTC, merged

2022-11-17 14:06 UTC, KitaharaMugiro commented
@web3rakko ありがとうございます！マージしました！

2022-11-18 00:46 UTC, web3rakko commented
@KitaharaMugiro 
承知しました、ありがとうございます！